---
SampleTitle: "FHC_numu_NDGAr"
SampleType: "BeamNDGAr"

POT: 1.0e+21
MaCh3ModeConfig: "Configs/CovObjs/MaCh3Modes.yaml"
SampleName: "ND_GAr"

BinningFile: "Configs/Samples/BeamParameterBinning.yaml"

Binning:
  XVarStr: "TrueNeutrinoEnergy"
  XVarBins: [0., 0.25, 0.5, 0.75, 1., 1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 4.25, 4.5, 4.75, 5., 5.25, 5.5, 5.75, 6., 6.25, 6.5, 6.75, 7., 7.25, 7.5, 7.75, 8., 8.25, 8.5, 8.75, 9., 9.25, 9.5, 9.75, 10., 1000.]

DetectorVariables:
  B_field: 0.5
  momentum_resolution_threshold: 0.05
  pixel_spacing: 6.
  spatial_resolution: 2.5
  adc_sampling_frequency: 20.
  drift_velocity: 3.011
  TPCFidLength: 209.
  TPCFidRadius: 160.0
  TPCInstrumentedLength: 250.
  TPCInstrumentedRadius: 260.
  ECALInnerRadius: 278.04
  ECALOuterRadius: 322.252
  ECALEndCapStart: 329.25
  ECALEndCapEnd: 374.4
  downsampling: 1
  EDepCrit: 0.002 # Max energy for a contained shower to deposit in the outer crit_layers (GeV)
  CritLayers: 2 # Number of layers defining this outer region

InputFiles:
  mtupleprefix: "Inputs/DUNE_NDGAr_AnaTrees/NDGAr_FHC_ger_"
  mtuplesuffix: "_numuselec_geant.root"
  splineprefix: ""
  splinesuffix: ""

NuOsc:
  NuOscConfigFile: "Configs/NuOsc/CUDAProb3Linear.yaml"
  EqualBinningPerOscChannel: true

SubSamples:
  - Name: "FHC_numu_x_numu"
    LatexName: "FHC_numu_x_numu"
    mtuplefile: "numu_x_numu"
      # splinefile: "numu_x_numu"
    splinefile: ""
    nutype: 14
    oscnutype: 14
